# Generated by Django 3.1.5 on 2021-03-27 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('caid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('startDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ratio', models.IntegerField()),
            ],
            options={
                'db_table': 'discount',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('deliveryAddress', models.TextField()),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderHasProducts',
            fields=[
                ('ohid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('IN-TRANSIT', 'In-transit'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled'), ('RETURNED', 'Returned')], default='PROCESSING', max_length=200)),
                ('oid', models.ForeignKey(db_column='order', default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.order')),
            ],
            options={
                'db_table': 'orderhasproducts',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('taxID', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('approved', models.BooleanField()),
                ('ohid', models.ForeignKey(db_column='orderhasproducts', default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.orderhasproducts')),
            ],
            options={
                'db_table': 'refundrequest',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('material', models.CharField(choices=[('18K GOLD', '18K GOLD'), ('14K GOLD', '14K GOLD'), ('10K GOLD', '10K GOLD')], default='18K GOLD', max_length=200)),
                ('productionCost', models.IntegerField()),
                ('size', models.IntegerField()),
                ('color', models.CharField(choices=[('GOLD', 'GOLD'), ('SILVER', 'SILVER'), ('ROSE', 'ROSE')], default='GOLD', max_length=200)),
                ('stock', models.IntegerField()),
                ('warranty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('caid', models.ForeignKey(db_column='category', default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
                ('did', models.OneToOneField(db_column='discount', default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.discount')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='orderhasproducts',
            name='pid',
            field=models.ForeignKey(db_column='products', default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.products'),
        ),
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.ForeignKey(db_column='users', default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.users'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('paidAmount', models.IntegerField()),
                ('address', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('isActive', models.BooleanField()),
                ('oid', models.OneToOneField(db_column='order', default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.order')),
                ('uid', models.ForeignKey(db_column='users', default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('coid', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=200)),
                ('rating', models.PositiveIntegerField(choices=[('1', ''), ('2', ''), ('3', ''), ('4', ''), ('5', '')])),
                ('approved', models.BooleanField()),
                ('pid', models.ForeignKey(db_column='products', default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.products')),
                ('uid', models.ForeignKey(db_column='user', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('pid', models.ForeignKey(db_column='products', default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.products')),
                ('uid', models.ForeignKey(db_column='users', default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
