# Generated by Django 3.1.5 on 2021-04-07 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='did',
            field=models.OneToOneField(blank=True, db_column='discount', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.discount'),
        ),
    ]
