# Generated by Django 3.1.5 on 2021-04-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210407_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='avgRating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
