# Generated by Django 3.1.5 on 2021-04-16 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_comments_datetimeadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uid',
            field=models.ForeignKey(db_column='user', default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.users'),
        ),
    ]
