# Generated by Django 3.1.5 on 2021-04-22 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='caid',
            field=models.OneToOneField(db_column='category', default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.category'),
        ),
    ]
