# Generated by Django 3.1.5 on 2021-04-22 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210422_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='caid',
            field=models.ForeignKey(db_column='category', default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.category'),
        ),
    ]
