# Generated by Django 3.1.5 on 2021-04-27 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210422_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.AlterField(
            model_name='products',
            name='caid',
            field=models.ForeignKey(db_column='category', default=9, on_delete=django.db.models.deletion.CASCADE, to='backend.category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='did',
            field=models.OneToOneField(blank=True, db_column='discount', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.discount'),
        ),
    ]
