# Generated by Django 3.1.5 on 2021-04-28 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210427_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='avgRating',
        ),
        migrations.AddField(
            model_name='products',
            name='ratingCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='totalRating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='dateTimeAdded',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
