# Generated by Django 3.1.5 on 2021-05-22 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210428_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, '')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryAddress',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
        ),
    ]
