# Generated by Django 3.1.5 on 2021-05-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210522_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='oid',
            field=models.OneToOneField(db_column='order', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.order'),
        ),
    ]
