# Generated by Django 3.2 on 2021-05-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20210523_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhasproducts',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('IN-TRANSIT', 'In-transit'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled'), ('RETURNED', 'Returned'), ('IN-REVIEW', 'In-review')], default='PROCESSING', max_length=200),
        ),
    ]
