# Generated by Django 3.1.5 on 2021-06-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_orderhasproducts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
